# Generated by Django 6.0.6 on 2026-07-24 10:01
# Hand-edited: reordered so the legacy plaintext `pin_code` is hashed into the
# new `pin_code_hash` field via RunPython *before* the old column is dropped —
# otherwise the data would be gone before it could be migrated.

import django.db.models.deletion
from django.contrib.auth.hashers import make_password
from django.db import migrations, models

# Only these roles ever carry a working terminal PIN. Super Admin/Admin/Rahbar
# never log into the terminal — any leftover PIN value on those accounts is
# dropped rather than hashed (spec: "PIN kodlar e'tiborsiz qoldirilsin").
_TERMINAL_CAPABLE_ROLES = {"manager", "operator", "warehouse"}


def hash_legacy_pins(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    legacy_users = User.objects.exclude(pin_code__isnull=True).exclude(pin_code="")
    for user in legacy_users:
        if user.role in _TERMINAL_CAPABLE_ROLES:
            user.pin_code_hash = make_password(user.pin_code)
            user.save(update_fields=["pin_code_hash"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('manufacturing', '0002_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(choices=[('faol', 'Faol'), ('vacation', "Ta'til"), ('sick', 'Kasallik'), ('terminated', "Bo'shatilgan")], default='faol', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='hired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_departments',
            field=models.ManyToManyField(blank=True, related_name='managers', to='manufacturing.tsex'),
        ),
        migrations.AddField(
            model_name='user',
            name='multi_shift_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_code_hash',
            field=models.CharField(blank=True, help_text='Terminal PIN kodining xavfsiz hashi', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.shift'),
        ),
        migrations.AddField(
            model_name='user',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='+', to='manufacturing.shift'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('middle', "O'rta"), ('senior', 'Senior')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('operator', 'Operator'), ('master', 'Usta'), ('adjuster', 'Sozlovchi'), ('welder', 'Payvandchi'), ('cutter', 'Kesuvchi'), ('assembler', "Yig'uvchi"), ('packer', 'Qadoqlovchi'), ('other', 'Boshqa')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uses_terminal',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(hash_legacy_pins, noop_reverse),
        migrations.RemoveField(
            model_name='user',
            name='pin_code',
        ),
    ]
