# Generated by Django 6.0.6 on 2026-07-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_pin_code_user_employment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hired_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='multi_shift_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shifts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill_level',
        ),
    ]
