# Generated by Django 6.0.6 on 2026-07-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phone_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('director', 'Rahbar / Direktor'), ('manager', 'Ishlab chiqarish menejeri'), ('master', "Master / Tsex boshlig'i"), ('technologist', 'Texnolog / Konstruktor'), ('operator', 'Operator / Usta'), ('packaging', 'Qadoqlash operatori'), ('warehouse', 'Omborchi'), ('sysadmin', 'Tizim administratori')], default='operator', max_length=20),
        ),
    ]
