# Generated by Django 6.0.6 on 2026-07-30 10:42

import accounts.models
from django.db import migrations, models


def backfill_badge_tokens(apps, schema_editor):
    """Existing employees (pre-dating this feature) all share the same blank
    badge_token — give each a unique one before the unique constraint below
    is applied, or that ALTER TABLE fails on the very first duplicate."""
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(badge_token=""):
        user.badge_token = accounts.models.generate_badge_token()
        user.save(update_fields=["badge_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_assigned_machines_through'),
    ]

    operations = [
        migrations.RunPython(backfill_badge_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='badge_token',
            field=models.CharField(default=accounts.models.generate_badge_token, editable=False, help_text='QR badge token — xodimni terminalda/QR orqali aniqlash uchun noyob token', max_length=64, unique=True),
        ),
    ]
