# Generated by Django 6.0.6 on 2026-07-17 13:17

import django.core.validators
from django.db import migrations, models


def clear_nonstandard_pin_codes(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    invalid_ids = [
        user_id
        for user_id, pin_code in User.objects.exclude(pin_code__isnull=True).values_list('id', 'pin_code')
        if len(pin_code) != 4 or not pin_code.isascii() or not pin_code.isdecimal()
    ]
    User.objects.filter(id__in=invalid_ids).update(pin_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pin_code_unique'),
    ]

    operations = [
        migrations.RunPython(clear_nonstandard_pin_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='pin_code',
            field=models.CharField(blank=True, help_text='Terminal PIN kodi (4 ta raqam)', max_length=4, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="PIN kod aynan 4 ta raqamdan iborat bo'lishi kerak.", regex='^[0-9]{4}$')]),
        ),
    ]
