# Generated by Django 6.0.6 on 2026-07-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTypeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('material_type', models.CharField(blank=True, max_length=100)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='catalog.producttype')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
