# Generated by Django 6.0.6 on 2026-07-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('panel', 'Plita'), ('edge_band', 'Kromka'), ('linear', 'Chiziqli material'), ('accessory', 'Furnitura'), ('other', 'Boshqa')], default='other', max_length=16)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['source_system', 'external_id'], name='catalog_mat_source__d86dc5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('source_system', ''), _negated=True), models.Q(('external_id', ''), _negated=True)), fields=('source_system', 'external_id', 'category'), name='unique_material_source_identity')],
            },
        ),
    ]
