# Generated by Django 6.0.6 on 2026-07-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_material'),
        ('orders', '0006_remove_order_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttypedetail',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='ProductTypeDetail',
        ),
    ]
