# Generated by Django 6.0.6 on 2026-08-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanevent',
            name='status',
            field=models.CharField(choices=[('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi'), ('conflict', 'Muammoli holat'), ('undone', 'Bekor qilindi')], default='accepted', max_length=16),
        ),
    ]
