# Generated by Django 6.0.6 on 2026-07-07 09:50

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('label_width_mm', models.PositiveSmallIntegerField(default=70)),
                ('label_height_mm', models.PositiveSmallIntegerField(default=50)),
            ],
            options={
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(default=orders.models.generate_order_no, max_length=32, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Past'), ('normal', 'Oddiy'), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Yangi'), ('approved', 'Tasdiqlangan'), ('in_production', 'Tsexda ishlab chiqarilmoqda'), ('partially_ready', 'Qisman tayyor'), ('ready_for_packaging', 'Qadoqlashga tayyor'), ('packaging', 'Qadoqlanmoqda'), ('warehouse', 'Tayyor omborda'), ('delivered', 'Mijozga topshirildi'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=24)),
                ('external_system', models.CharField(blank=True, max_length=32)),
                ('external_order_id', models.CharField(blank=True, max_length=64)),
                ('external_customer_id', models.CharField(blank=True, max_length=64)),
                ('approved_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('approved_deadline', models.DateField(blank=True, null=True)),
                ('customer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('odoo_sync_status', models.CharField(choices=[('not_connected', 'not_connected'), ('pending', 'pending'), ('synced', 'synced'), ('failed', 'failed')], default='not_connected', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('edge_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('drilling_count', models.PositiveIntegerField(default=0)),
                ('qr_token', models.CharField(default=orders.models.generate_qr_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Tayyor'), ('blocked', 'Bloklangan'), ('conflict', 'Konflikt')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PartRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_index', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Bajarildi'), ('blocked', 'Bloklangan'), ('not_required', 'Kerak emas')], default='pending', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['part', 'sequence_index'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
