# Generated by Django 6.0.6 on 2026-07-22 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('orders', '0001_initial'),
        ('packaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='packaging.package'),
        ),
        migrations.AddField(
            model_name='label',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_orders', to='manufacturing.operation'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.producttype'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderstageprogress',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_order_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstageprogress',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderstageprogress',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_stage_progress', to='manufacturing.operation'),
        ),
        migrations.AddField(
            model_name='part',
            name='current_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_parts', to='manufacturing.operation'),
        ),
        migrations.AddField(
            model_name='part',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='part',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_detail', to='orders.part'),
        ),
        migrations.AddField(
            model_name='label',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='orders.part'),
        ),
        migrations.AddField(
            model_name='partroute',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partroute',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_routes', to='manufacturing.machine'),
        ),
        migrations.AddField(
            model_name='partroute',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_routes', to='manufacturing.operation'),
        ),
        migrations.AddField(
            model_name='partroute',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='orders.part'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order'),
        ),
        migrations.AddField(
            model_name='part',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='orders.product'),
        ),
        migrations.AlterUniqueTogether(
            name='orderstageprogress',
            unique_together={('order', 'stage')},
        ),
        migrations.AlterUniqueTogether(
            name='partroute',
            unique_together={('part', 'operation')},
        ),
    ]
