# Generated by Django 6.0.6 on 2026-07-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_qr_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approved_deadline',
        ),
        migrations.RemoveField(
            model_name='order',
            name='approved_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='external_customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='external_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='external_system',
        ),
        migrations.RemoveField(
            model_name='order',
            name='odoo_sync_status',
        ),
    ]
