# Generated by Django 6.0.6 on 2026-07-30 10:10

from django.db import migrations, models


def migrate_low_priority_to_normal(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(priority='low').update(priority='normal')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_product_quantity'),
    ]

    operations = [
        migrations.RunPython(migrate_low_priority_to_normal, noop),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('normal', 'Oddiy'), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='normal', max_length=16),
        ),
    ]
