# Generated by Django 6.0.6 on 2026-07-31 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_material'),
        ('orders', '0004_normalize_priority_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='material_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='catalog.material'),
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_project_uuid', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='orders.product')),
            ],
            options={
                'ordering': ['product', 'version'],
                'unique_together': {('product', 'version')},
            },
        ),
        migrations.CreateModel(
            name='GibLabImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(default='giblab', max_length=32)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_checksum', models.CharField(max_length=64, unique=True)),
                ('project_uuid', models.CharField(blank=True, max_length=64)),
                ('file_version', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('uploaded', 'Yuklandi'), ('validated', 'Tekshirildi'), ('importing', 'Import qilinmoqda'), ('completed', 'Yakunlandi'), ('failed', 'Xatolik')], default='uploaded', max_length=16)),
                ('statistics', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giblab_import_batches', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('part', 'Detal'), ('material', 'Material'), ('edge_band', 'Kromka')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('edge_side', models.CharField(blank=True, choices=[('top', 'Yuqori'), ('bottom', 'Past'), ('left', 'Chap'), ('right', "O'ng")], max_length=16, null=True)),
                ('source_external_id', models.CharField(blank=True, max_length=64)),
                ('sequence_index', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.bom')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='catalog.material')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='orders.part')),
                ('target_part', models.ForeignKey(blank=True, help_text='For EDGE_BAND rows: which part this edge belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_edge_items', to='orders.part')),
            ],
            options={
                'ordering': ['bom', 'sequence_index', 'id'],
                'indexes': [models.Index(fields=['bom', 'item_type'], name='orders_bomi_bom_id_e22a97_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('edge_side__isnull', False), ('item_type', 'edge_band')), models.Q(models.Q(('item_type', 'edge_band'), _negated=True), ('edge_side__isnull', True)), _connector='OR'), name='bomitem_edge_side_iff_edge_band')],
            },
        ),
    ]
