# Generated by Django 6.0.6 on 2026-07-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0004_remove_odoo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.producttype'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('material_type', models.CharField(blank=True, max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
