# Generated by Django 6.0.6 on 2026-07-17 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_product_type_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='part',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_detail', to='orders.part'),
        ),
    ]
