# Generated by Django 6.0.6 on 2026-07-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_part_material_ref_bom_giblabimportbatch_bomitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_type',
        ),
    ]
