# Generated by Django 6.0.6 on 2026-07-07 09:50

import django.db.models.deletion
import packaging.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_no', models.CharField(default=packaging.models.generate_package_no, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('completed', 'Yakunlangan'), ('warehouse', 'Omborda'), ('delivered', 'Topshirildi')], default='open', max_length=16)),
                ('qr_token', models.CharField(default=packaging.models.generate_package_no, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packaging.package')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='orders.part')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('package', 'part')},
            },
        ),
    ]
