# Generated by Django 6.0.6 on 2026-07-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('offline_ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('measure_unit', models.CharField(choices=[('m2', 'm²'), ('meter', 'metr'), ('piece', 'dona'), ('package', 'qadoq')], max_length=16)),
                ('qr_scan_required', models.BooleanField(default=True)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Tsex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tsexes', to='manufacturing.factory')),
            ],
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'Ishlayapti'), ('inactive', 'Noaktiv'), ('maintenance', "Ta'mirda"), ('stopped', "To'xtagan")], default='active', max_length=16)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workstations', to='manufacturing.operation')),
                ('tsex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='manufacturing.tsex')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('label_width_mm', models.PositiveSmallIntegerField(default=70)),
                ('label_height_mm', models.PositiveSmallIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='manufacturing.workstation')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('maintenance', 'maintenance'), ('broken', 'broken')], default='active', max_length=16)),
                ('terminal_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='manufacturing.device')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='manufacturing.operation')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='manufacturing.printer')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='manufacturing.workstation')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='manufacturing.workstation'),
        ),
    ]
