# Generated by Django 6.0.6 on 2026-07-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='capacity_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Soatiga rejalashtirilgan quvvat (operatsiya birligida: m2/metr/dona)', max_digits=10, null=True),
        ),
    ]
