# Generated by Django 6.0.6 on 2026-07-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_machine_capacity_per_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsex',
            name='factory',
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
    ]
