# Generated by Django 6.0.6 on 2026-07-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_hired_at_remove_user_multi_shift_enabled_and_more'),
        ('manufacturing', '0003_seed_shifts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
